name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 使用 outputs, 这是在步骤间传递变量最可靠的方式
      - name: Prepare image metadata
        id: meta
        run: |
          echo "image_name=$(echo 'ghcr.io/${{ github.repository_owner }}/api-conversion' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 使用 outputs 中的变量来构建最终标签
          tags: ${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.tag }}
